### Day 3

### Task 1 : Profile row and column counts per file (sampled findings — not exact)

In [3]:
### Datasets in our Project

### We have three CSV files:

### ai_company_adoption.csv
#### Main dataset containing company-level information.
#### ai_industry_summary.csv
##### Contains industry-level summarized statistics.
###### country_ai_index.csv
#### Contains country-level AI adoption information.

### For each file, you need to find:

## Number of rows
## Number of columns

In [5]:
import os
print(os.getcwd())

C:\Users\chinn\OneDrive\Desktop\data analytics internship\AIPulse-Enterprise-AI-Adoption-Business-Performance-Analytics\notebooks

In [3]:
import pandas as pd

company = pd.read_csv("../data/raw/ai_company_adoption.csv")
industry = pd.read_csv("../data/raw/ai_industry_summary.csv")
country = pd.read_csv("../data/raw/country_ai_index.csv")

print(company.shape)
print(industry.shape)
print(country.shape)

(150000, 43)
(9, 8)
(30, 8)

In [5]:
company.shape   #### it indicate main dataset

(150000, 43)

In [6]:
company.head()

,response_id,company_id,survey_year,quarter,country,region,industry,company_size,num_employees,annual_revenue_usd_millions,...,productivity_change_percent,jobs_displaced,jobs_created,reskilled_employees,revenue_growth_percent,cost_reduction_percent,innovation_score,customer_satisfaction,survey_source,data_collection_method
0,1,COMP-00001,2023,Q1,Italy,Europe,Education,Startup,57,48.31,...,2.65,1,1,3,2.52,9.45,53,5.20,WEF Survey,API Scrape
1,2,COMP-00001,2023,Q2,Italy,Europe,Education,Startup,57,48.31,...,5.77,2,2,5,4.77,0.00,51,6.98,McKinsey Report,Phone Interview
2,3,COMP-00001,2023,Q3,Italy,Europe,Education,Startup,57,48.31,...,6.94,3,3,2,12.87,9.74,40,4.12,Internal Corporate Survey,Research Compilation
3,4,COMP-00001,2023,Q4,Italy,Europe,Education,Startup,57,48.31,...,5.32,1,1,2,8.19,0.00,51,5.72,Internal Corporate Survey,Research Compilation
4,5,COMP-00001,2024,Q1,Italy,Europe,Education,Startup,57,48.31,...,6.32,2,3,6,11.30,9.02,43,6.31,McKinsey Report,Research Compilation

In [7]:
company.tail()

,response_id,company_id,survey_year,quarter,country,region,industry,company_size,num_employees,annual_revenue_usd_millions,...,productivity_change_percent,jobs_displaced,jobs_created,reskilled_employees,revenue_growth_percent,cost_reduction_percent,innovation_score,customer_satisfaction,survey_source,data_collection_method
149995,159996,COMP-10000,2025,Q4,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,19.01,1292,1027,1766,9.44,9.52,62,5.68,McKinsey Report,Phone Interview
149996,159997,COMP-10000,2026,Q1,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,15.56,466,883,803,10.65,6.94,56,5.57,Internal Corporate Survey,Research Compilation
149997,159998,COMP-10000,2026,Q2,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,13.38,1360,1474,1779,5.52,0.32,48,7.56,WEF Survey,API Scrape
149998,159999,COMP-10000,2026,Q3,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,12.75,1358,887,1648,11.87,7.85,69,6.00,WEF Survey,Research Compilation
149999,160000,COMP-10000,2026,Q4,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,14.42,1529,1501,2409,11.89,10.82,65,7.30,WEF Survey,API Scrape

In [8]:
company.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 43 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   response_id                  150000 non-null  int64
 1   company_id                   150000 non-null  object
 2   survey_year                  150000 non-null  int64
 3   quarter                      150000 non-null  object
 4   country                      150000 non-null  object
 5   region                       150000 non-null  object
 6   industry                     150000 non-null  object
 7   company_size                 150000 non-null  object
 8   num_employees                150000 non-null  int64
 9   annual_revenue_usd_millions  150000 non-null  float64
 10  company_founding_year        150000 non-null  int64
 11  company_age                  150000 non-null  int64
 12  company_age_group            150000 non-null  object
 13  ai_adoption_rate             150000 non-null  float64
 14  ai_adoption_stage            150000 non-null  object
 15  years_using_ai               150000 non-null  int64
 16  ai_primary_tool              150000 non-null  object
 17  num_ai_tools_used            150000 non-null  int64
 18  ai_use_case                  150000 non-null  object
 19  ai_projects_active           150000 non-null  int64
 20  ai_training_hours            150000 non-null  float64
 21  ai_budget_percentage         150000 non-null  float64
 22  ai_maturity_score            150000 non-null  float64
 23  ai_failure_rate              150000 non-null  float64
 24  ai_investment_per_employee   150000 non-null  float64
 25  regulatory_compliance_score  150000 non-null  int64
 26  data_privacy_level           150000 non-null  object
 27  ai_ethics_committee          150000 non-null  object
 28  ai_risk_management_score     150000 non-null  int64
 29  remote_work_percentage       150000 non-null  float64
 30  employee_satisfaction_score  150000 non-null  float64
 31  task_automation_rate         150000 non-null  float64
 32  time_saved_per_week          150000 non-null  float64
 33  productivity_change_percent  150000 non-null  float64
 34  jobs_displaced               150000 non-null  int64
 35  jobs_created                 150000 non-null  int64
 36  reskilled_employees          150000 non-null  int64
 37  revenue_growth_percent       150000 non-null  float64
 38  cost_reduction_percent       150000 non-null  float64
 39  innovation_score             150000 non-null  int64
 40  customer_satisfaction        150000 non-null  float64
 41  survey_source                150000 non-null  object
 42  data_collection_method       150000 non-null  object
dtypes: float64(15), int64(14), object(14)
memory usage: 49.2+ MB

In [9]:
company.columns

Index(['response_id', 'company_id', 'survey_year', 'quarter', 'country',
       'region', 'industry', 'company_size', 'num_employees',
       'annual_revenue_usd_millions', 'company_founding_year', 'company_age',
       'company_age_group', 'ai_adoption_rate', 'ai_adoption_stage',
       'years_using_ai', 'ai_primary_tool', 'num_ai_tools_used', 'ai_use_case',
       'ai_projects_active', 'ai_training_hours', 'ai_budget_percentage',
       'ai_maturity_score', 'ai_failure_rate', 'ai_investment_per_employee',
       'regulatory_compliance_score', 'data_privacy_level',
       'ai_ethics_committee', 'ai_risk_management_score',
       'remote_work_percentage', 'employee_satisfaction_score',
       'task_automation_rate', 'time_saved_per_week',
       'productivity_change_percent', 'jobs_displaced', 'jobs_created',
       'reskilled_employees', 'revenue_growth_percent',
       'cost_reduction_percent', 'innovation_score', 'customer_satisfaction',
       'survey_source', 'data_collection_method'],
      dtype='object')

In [10]:
len(company.columns)

43

In [11]:
company.dtypes

response_id                      int64
company_id                      object
survey_year                      int64
quarter                         object
country                         object
region                          object
industry                        object
company_size                    object
num_employees                    int64
annual_revenue_usd_millions    float64
company_founding_year            int64
company_age                      int64
company_age_group               object
ai_adoption_rate               float64
ai_adoption_stage               object
years_using_ai                   int64
ai_primary_tool                 object
num_ai_tools_used                int64
ai_use_case                     object
ai_projects_active               int64
ai_training_hours              float64
ai_budget_percentage           float64
ai_maturity_score              float64
ai_failure_rate                float64
ai_investment_per_employee     float64
regulatory_compliance_score      int64
data_privacy_level              object
ai_ethics_committee             object
ai_risk_management_score         int64
remote_work_percentage         float64
employee_satisfaction_score    float64
task_automation_rate           float64
time_saved_per_week            float64
productivity_change_percent    float64
jobs_displaced                   int64
jobs_created                     int64
reskilled_employees              int64
revenue_growth_percent         float64
cost_reduction_percent         float64
innovation_score                 int64
customer_satisfaction          float64
survey_source                   object
data_collection_method          object
dtype: object

In [12]:
company.describe()

,response_id,survey_year,num_employees,annual_revenue_usd_millions,company_founding_year,company_age,ai_adoption_rate,years_using_ai,num_ai_tools_used,ai_projects_active,...,task_automation_rate,time_saved_per_week,productivity_change_percent,jobs_displaced,jobs_created,reskilled_employees,revenue_growth_percent,cost_reduction_percent,innovation_score,customer_satisfaction
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,...,150000.000000,150000.000000,150000.000000,150000.00000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000
mean,79961.106207,2024.500987,2342.376580,1180.345751,2005.993767,18.507220,36.414726,4.931580,2.315120,6.270693,...,19.761744,6.267406,9.266996,111.36984,117.882507,181.642700,4.606486,4.814909,55.199920,5.420619
std,46158.813039,1.118013,4754.424755,2391.471420,9.473220,9.539367,14.544096,2.429316,0.946826,3.500142,...,9.222562,2.977495,5.637067,255.83778,261.650245,417.929587,5.318773,3.383086,8.593423,1.047142
min,1.000000,2023.000000,10.000000,1.010000,1990.000000,1.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,-5.000000,0.000000,40.000000,1.000000
25%,40020.750000,2024.000000,69.000000,33.880000,1998.000000,10.000000,26.430000,3.000000,2.000000,4.000000,...,13.360000,4.180000,5.070000,2.00000,3.000000,3.000000,0.780000,2.120000,49.000000,4.700000
50%,79937.500000,2025.000000,349.000000,184.160000,2006.000000,18.000000,36.320000,5.000000,2.000000,6.000000,...,19.700000,6.230000,9.060000,10.00000,12.000000,16.000000,4.480000,4.620000,55.000000,5.410000
75%,119913.250000,2026.000000,884.000000,444.150000,2014.000000,27.000000,46.200000,7.000000,3.000000,9.000000,...,26.020000,8.290000,13.120000,41.00000,41.000000,64.000000,8.240000,7.130000,61.000000,6.130000
max,160000.000000,2026.000000,19970.000000,9996.730000,2022.000000,36.000000,100.000000,10.000000,6.000000,20.000000,...,59.630000,19.150000,34.360000,2417.00000,1980.000000,3881.000000,30.000000,20.790000,97.000000,9.760000

#### task 2 
#### Inspect data types for detected columns

In [15]:

print("Company Dataset")
company.info()
print("-----------------------------------------")

print("\nIndustry Dataset")
industry.info()
print("-----------------------------------------")
print("\nCountry Dataset")
country.info()

Company Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 43 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   response_id                  150000 non-null  int64
 1   company_id                   150000 non-null  object
 2   survey_year                  150000 non-null  int64
 3   quarter                      150000 non-null  object
 4   country                      150000 non-null  object
 5   region                       150000 non-null  object
 6   industry                     150000 non-null  object
 7   company_size                 150000 non-null  object
 8   num_employees                150000 non-null  int64
 9   annual_revenue_usd_millions  150000 non-null  float64
 10  company_founding_year        150000 non-null  int64
 11  company_age                  150000 non-null  int64
 12  company_age_group            150000 non-null  object
 13  ai_adoption_rate             150000 non-null  float64
 14  ai_adoption_stage            150000 non-null  object
 15  years_using_ai               150000 non-null  int64
 16  ai_primary_tool              150000 non-null  object
 17  num_ai_tools_used            150000 non-null  int64
 18  ai_use_case                  150000 non-null  object
 19  ai_projects_active           150000 non-null  int64
 20  ai_training_hours            150000 non-null  float64
 21  ai_budget_percentage         150000 non-null  float64
 22  ai_maturity_score            150000 non-null  float64
 23  ai_failure_rate              150000 non-null  float64
 24  ai_investment_per_employee   150000 non-null  float64
 25  regulatory_compliance_score  150000 non-null  int64
 26  data_privacy_level           150000 non-null  object
 27  ai_ethics_committee          150000 non-null  object
 28  ai_risk_management_score     150000 non-null  int64
 29  remote_work_percentage       150000 non-null  float64
 30  employee_satisfaction_score  150000 non-null  float64
 31  task_automation_rate         150000 non-null  float64
 32  time_saved_per_week          150000 non-null  float64
 33  productivity_change_percent  150000 non-null  float64
 34  jobs_displaced               150000 non-null  int64
 35  jobs_created                 150000 non-null  int64
 36  reskilled_employees          150000 non-null  int64
 37  revenue_growth_percent       150000 non-null  float64
 38  cost_reduction_percent       150000 non-null  float64
 39  innovation_score             150000 non-null  int64
 40  customer_satisfaction        150000 non-null  float64
 41  survey_source                150000 non-null  object
 42  data_collection_method       150000 non-null  object
dtypes: float64(15), int64(14), object(14)
memory usage: 49.2+ MB
-----------------------------------------

Industry Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   industry                         9 non-null      object
 1   avg_ai_adoption_rate             9 non-null      float64
 2   avg_productivity_change_percent  9 non-null      float64
 3   avg_ai_maturity_score            9 non-null      float64
 4   avg_ai_failure_rate              9 non-null      float64
 5   avg_jobs_displaced               9 non-null      float64
 6   avg_jobs_created                 9 non-null      float64
 7   avg_customer_satisfaction        9 non-null      float64
dtypes: float64(7), object(1)
memory usage: 708.0+ bytes
-----------------------------------------

Country Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   country                     30 non-null     object
 1   region                      30 non-null     object
 2   gdp_per_capita              30 non-null     float64
 3   internet_penetration        30 non-null     float64
 4   digital_maturity_index      30 non-null     float64
 5   country_ai_policy           30 non-null     object
 6   ai_patent_filings_2024      30 non-null     int64
 7   ai_researchers_per_million  30 non-null     float64
dtypes: float64(4), int64(1), object(3)
memory usage: 2.0+ KB

In [16]:
company.dtypes.value_counts()

float64    15
int64      14
object     14
Name: count, dtype: int64

In [17]:
company.nunique()

response_id                    150000
company_id                      10000
survey_year                         4
quarter                             4
country                            30
region                              6
industry                            9
company_size                        3
num_employees                    2850
annual_revenue_usd_millions      8688
company_founding_year              33
company_age                        36
company_age_group                   4
ai_adoption_rate                 7829
ai_adoption_stage                   4
years_using_ai                     11
ai_primary_tool                     6
num_ai_tools_used                   6
ai_use_case                         8
ai_projects_active                 21
ai_training_hours                6635
ai_budget_percentage             2258
ai_maturity_score                 847
ai_failure_rate                  3760
ai_investment_per_employee     148339
regulatory_compliance_score        61
data_privacy_level                  3
ai_ethics_committee                 2
ai_risk_management_score           56
remote_work_percentage           8115
employee_satisfaction_score       604
task_automation_rate             4831
time_saved_per_week              1655
productivity_change_percent      2816
jobs_displaced                   1723
jobs_created                     1651
reskilled_employees              2610
revenue_growth_percent           2742
cost_reduction_percent           1712
innovation_score                   53
customer_satisfaction             773
survey_source                       4
data_collection_method              4
dtype: int64

### task 3 : Log missing-value counts per column

In [18]:
company.isnull().sum()

response_id                    0
company_id                     0
survey_year                    0
quarter                        0
country                        0
region                         0
industry                       0
company_size                   0
num_employees                  0
annual_revenue_usd_millions    0
company_founding_year          0
company_age                    0
company_age_group              0
ai_adoption_rate               0
ai_adoption_stage              0
years_using_ai                 0
ai_primary_tool                0
num_ai_tools_used              0
ai_use_case                    0
ai_projects_active             0
ai_training_hours              0
ai_budget_percentage           0
ai_maturity_score              0
ai_failure_rate                0
ai_investment_per_employee     0
regulatory_compliance_score    0
data_privacy_level             0
ai_ethics_committee            0
ai_risk_management_score       0
remote_work_percentage         0
employee_satisfaction_score    0
task_automation_rate           0
time_saved_per_week            0
productivity_change_percent    0
jobs_displaced                 0
jobs_created                   0
reskilled_employees            0
revenue_growth_percent         0
cost_reduction_percent         0
innovation_score               0
customer_satisfaction          0
survey_source                  0
data_collection_method         0
dtype: int64

In [19]:
company.isnull().sum().sum()

np.int64(0)

#### task 4 Identify duplicates using response_id, company_id

In [22]:
company["response_id"].duplicated().sum()

np.int64(0)

In [23]:
company["company_id"].duplicated().sum()

np.int64(140000)

In [25]:
company["company_id"].value_counts().head(10)

company_id
COMP-00001    16
COMP-05081    16
COMP-05068    16
COMP-05060    16
COMP-05059    16
COMP-05058    16
COMP-05056    16
COMP-05055    16
COMP-05053    16
COMP-05050    16
Name: count, dtype: int64

In [26]:
company.duplicated(subset=["response_id", "company_id"]).sum()

np.int64(0)

In [27]:
company["response_id"].is_unique

True

In [28]:
print("Total Rows:", len(company))
print("Unique Companies:", company["company_id"].nunique())

Total Rows: 150000
Unique Companies: 10000

In [29]:
company.duplicated(subset=["response_id", "company_id"]).sum()  #### combination of two

np.int64(0)